[theme]
base = "light"
primaryColor = "#FF5B24"
backgroundColor = "#FBFAF8"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#1F2328"
font = "sans serif"

[server]
headless = true
maxUploadSize = 20

[browser]
gatherUsageStats = false

